# treefmt.toml :: run `just fmt` (or `treefmt`) to format everything below.

[formatter.prettier-web]
command = "prettier"
options = ["--write"]
includes = [
  "assets/**/*.css",
  "assets/**/*.js",
  "exampleSite/**/*.css",
  "exampleSite/**/*.js",
  "exampleSite/**/*.yaml",
]

[formatter.gotmplfmt]
command = "gotmplfmt"
includes = ["layouts/**/*.html", "layouts/**/*.js"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
